# Generated by Django 4.2.7 on 2024-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_no', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('tax_no', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=8)),
            ],
        ),
    ]
